import {NullEngine,Scene,Vector3} from '@babylonjs/core';
import {writeFile,readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {loadHeadlessModel} from '../tests/model-helper.js';
// Keep ALL original scene nodes, materials and geometry byte-for-byte. The sole
// runtime adjustment is a shared vertical translation putting the main floor at 0.
const sourceURL=new URL('../client/public/assets/maps/depot.glb',import.meta.url);
const e=new NullEngine(),s=new Scene(e),c=await loadHeadlessModel(sourceURL,s);c.addAllToScene();
const offsetY=2.151349809814501;const triangles:number[][]=[];const seen=new Set<string>();
for(const mesh of c.meshes){if(!mesh.getTotalVertices())continue;mesh.computeWorldMatrix(true);const p=mesh.getPositionData()!,ix=mesh.getIndices()!;
  for(let i=0;i<ix.length;i+=3){const v=[0,1,2].map(k=>Vector3.TransformCoordinates(Vector3.FromArray(p,ix[i+k]*3),mesh.getWorldMatrix()).add(new Vector3(0,offsetY,0)));
    if(Vector3.Cross(v[1].subtract(v[0]),v[2].subtract(v[0])).lengthSquared()<1e-12)continue;
    const values=v.map(p=>p.asArray().map(n=>Math.round(n*100000)/100000));const key=values.map(v=>v.join(',')).sort().join(';');if(seen.has(key))continue;seen.add(key);triangles.push(values.flat());
  }
}
const hash=createHash('sha256').update(await readFile(sourceURL)).digest('hex');
await writeFile(new URL('../shared/depot-geometry.ts',import.meta.url),`// Generated by scripts/build-depot.ts from the complete uploaded GLB. Do not edit.\nexport const DEPOT_OFFSET_Y=${offsetY};\nexport const DEPOT_SOURCE_SHA256='${hash}';\nexport const DEPOT_TRIANGLES:number[][]=${JSON.stringify(triangles)};\n`);
console.log(`Full original map installed: ${c.meshes.filter(m=>m.getTotalVertices()).length} meshes, ${triangles.length} collision triangles. Main floor Y=0.`);s.dispose();e.dispose();
